@startuml
!theme mono


class Client  {
    - email_classifiers: list[EmailClassifierFacade]
    - data_set_loader: DatasetLoader
    - command_executor: CommandInvoker
    + __init__()
    + print_startup(): void
    + create_parser(): argparse.ArgumentParser
    + create_completer(): NestedCompleter
    + run_cli(): void
    + handle_command(args): bool
    - config_manager: ClassifierConfigSingleton
}

class CommandInvoker {
    - _command: Command
    + set_command(command: Command): void
    + execute_command(command: Command): void
    + undo(): void
}


class Command {
    + execute(): void
    + undo(): void
}

class AddEmailsCommand {
}

class ClassifyEmailCommand {
}

class ChangeStrategyCommand {
}

class AddPreprocessingCommand {
}

class TrainModelCommand {
}

class DisplayEvaluationCommand {
}

class EmailClassifierFacade {
}

Client o-- "1..*" EmailClassifierFacade : manages
Client o-- CommandInvoker
CommandInvoker o-- "1" Command : manages
Command <|-- AddEmailsCommand
Command <|-- ClassifyEmailCommand
Command <|-- ChangeStrategyCommand
Command <|-- AddPreprocessingCommand
Command <|-- TrainModelCommand
Command <|-- DisplayEvaluationCommand

Command --> EmailClassifierFacade :executes
Client --> Command :creates 

@enduml
