@startuml add_emails
!theme mono

actor Client
participant "AddEmailsCommand" as Command
participant "EmailClassifierFacade" as EmailClassifier
participant "DatasetLoader" as Loader

Client -> Command : execute(path)
Command -> EmailClassifier : add_emails(path)
EmailClassifier -> Loader : read_data(path)
Loader --> EmailClassifier : Return df
EmailClassifier -> Loader : renameColumns(df)
Loader --> EmailClassifier : Return df

@enduml