@startuml
!theme mono
left to right direction

actor "End user" as eu
actor "System administrator" as sa

rectangle EmailClassifier {
    usecase "Add customer emails to the system" as UC1
    usecase "Get classification result" as UC2
    usecase "Create different types of email classifiers" as UC3
    usecase "Change behaviours of email classifiers" as UC4
    usecase "Add preprocessing features" as UC5
    usecase "Display evaluation and perform analysis" as UC6
    usecase "Access configuration" as UC7
    usecase "Train machine learning model" as UC8

eu -- UC1
eu -- UC2
sa -- UC3
sa -- UC4
sa -- UC5
sa -- UC6
sa -- UC7
sa -- UC8
@enduml